version: '3'
services:
  mysql:
    image: mysql:8.0
    ports:
      - "3306:3306"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: altigee
      MYSQL_DATABASE: needoff
    volumes:
      - needoff-mysql-vol:/var/lib/mysql
    networks:
      - needoff-network

  needoff-api:
    image: needoff-api:latest
    ports:
      - "8080:8080"
    networks:
      - needoff-network

volumes:
  needoff-mysql-vol:
    driver: local

networks:
  needoff-network:
