FROM openjdk:11.0.3-stretch
ARG APPLICATION_FILENAME

COPY build/libs/$APPLICATION_FILENAME /application/$APPLICATION_FILENAME
WORKDIR /application

EXPOSE 8080
ENV APPLICATION_FILENAME $APPLICATION_FILENAME
ENTRYPOINT java -Dspring.profiles.active=docker -jar $APPLICATION_FILENAME
