version: '2'
services:
  mysql:
    image: mysql:8.0
    ports:
      - "3306:3306"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: altigee
      MYSQL_DATABASE: needoff
    volumes:
      - needoff-mysql-vol:/var/lib/mysql

volumes:
  needoff-mysql-vol:
    driver: local