needoff:
  jwt:
    accessTokenExpirationMinutes: 10080 # 1 week (dev value)
    refreshTokenExpirationMinutes: 20160 # 2 weeks (dev value)
    secretKey: "secret123"

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/needoff?allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: altigee
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL8Dialect
  jackson:
    serialization:
      indent_output : true
  flyway:
    locations: classpath:db/migration/mysql
    baseline-on-migrate: true

graphql:
  servlet:
    mapping: /graphql
    enabled: true
    corsEnabled: true
    exception-handlers-enabled: true
    contextSetting: PER_REQUEST_WITH_INSTRUMENTATION

graphiql:
  enabled: false

management:
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    ROOT: DEBUG
